services:
  - type: web
    name: pulseboard-api-gateway
    env: docker
    dockerfilePath: apps/api-gateway/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3001
      - fromGroup: pulseboard-env

  - type: web
    name: pulseboard-poller-service
    env: docker
    dockerfilePath: apps/poller-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3002
      - fromGroup: pulseboard-env

  - type: web
    name: pulseboard-ingestor-service
    env: docker
    dockerfilePath: apps/ingestor-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3003
      - fromGroup: pulseboard-env

  - type: web
    name: pulseboard-alert-service
    env: docker
    dockerfilePath: apps/alert-service/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3004
      - fromGroup: pulseboard-env

envVarGroups:
  - name: pulseboard-env
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: RUN_MIGRATIONS
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: INTERNAL_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: API_GATEWAY_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
